name: Build

on: [ push ]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '*'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Prepare
        run: yarn prepare:mainnet
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
