name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Set yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          # mind node_modules backup
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Run linter
        run: yarn lint:check

  commits:
      runs-on: ubuntu-latest

      steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v2
